enabled:
  - ordered_use
  - ereg_to_preg
  - concat_with_spaces
  - align_equals
  - align_double_arrow
  - whitespacy_lines
  - unused_use
  - ternary_spaces
  - standardize_not_equal
  - spaces_cast
  - remove_lines_between_uses
  - single_array_no_trailing_comma
  - remove_leading_slash_use
  - operators_spaces
  - phpdoc_indent
  - object_operator
  - multiline_array_trailing_comma
  - join_function
  - include
  - extra_empty_lines
  - empty_return
  - duplicate_semicolon
  - double_arrow_multiline_whitespaces
  - trailing_spaces
  - php_closing_tag
  - parenthesis
  - lowercase_constants
  - line_after_namespace
  - indentation
  - eof_ending
  - encoding

